baseURL = "https://leefuller.io/"
languageCode = "en-us"
title = "LeeFuller.io"
theme = "minimal-bootstrap-hugo-theme"
#disableKinds = ["taxonomies"]

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  description = "Lee Loves Rachel ♡♡♡"
  contentBackgroundColor = "#0e0b16"
  contentTextColor = "#e7dfdd"
  contentLinkColor = "#4717f6"
  contentLinkHoverColor = "#a239ca"
  navbarBackgroundColor = "#26232d"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  wrapperMaxWidth = "800px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  googleAnalytics = false
  cookieConsent = false
  includeBootstrapJs = false
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1
#  [[menu.nav]]
#  name = "Tags"
#  url = "/tags/"
#  weight = 2
  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 3
  [[menu.nav]]
  name = "Status"
  url = "https://status.leefuller.io/"
  weight = 4
  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 5

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
